import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'

export interface ExportRow { date: string; meal: string; vendor: string; planType: string; pax: number; basePrice: number; deliveryFee: number; courierType: string; shippingDistanceKm: number; packagingFee: number; packagingDeposit: number; depositStatus: string; addonItems: string; addonPrice: number; voucherCode: string; discount: number; paymentStatus: string; paymentMethod: string; onTimeStatus: string; qualityRating: number; packagingCondition: string; netTotal: number; menuNotes: string }
export interface PdfReportOptions { periodLabel?: string; budgetCap?: number; userName?: string }
const money = (value: number) => new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', maximumFractionDigits: 0 }).format(value)
const dateLabel = (value: string) => new Intl.DateTimeFormat('en-US', { month: 'short', day: '2-digit', year: 'numeric' }).format(new Date(`${value}T00:00:00`))

export function exportTransactionsPdf(rows: ExportRow[], options: PdfReportOptions = {}): void {
  const document = new jsPDF({ orientation: 'landscape', unit: 'pt', format: 'a3' }); const totalSpend = rows.reduce((sum, row) => sum + row.netTotal, 0); const totalPax = rows.reduce((sum, row) => sum + row.pax, 0); const average = totalPax ? totalSpend / totalPax : 0; const logistics = rows.reduce((sum, row) => sum + row.deliveryFee + row.packagingFee, 0); const deposits = rows.reduce((sum, row) => sum + row.packagingDeposit, 0); const discounts = rows.reduce((sum, row) => sum + row.discount, 0); const paid = rows.filter((row) => row.paymentStatus === 'Paid').length; const budgetUse = options.budgetCap ? totalSpend / options.budgetCap * 100 : 0
  document.setFillColor(32, 33, 36); document.rect(0, 0, 1191, 76, 'F'); document.setTextColor(255, 255, 255); document.setFontSize(22); document.text('Catering Pulse - Full Financial & Quality Audit Report', 40, 35); document.setFontSize(9); document.setTextColor(215, 210, 204); document.text(`${options.periodLabel ?? 'Selected period'} · ${options.userName ?? 'Personal workspace'} · Generated ${new Date().toLocaleString('id-ID')}`, 40, 56)
  autoTable(document, { startY: 94, theme: 'grid', head: [['Total Spend', 'Total Pax', 'Avg Cost/Pax', 'Logistics', 'Active Deposits', 'Discounts']], body: [[money(totalSpend), String(totalPax), money(average), money(logistics), money(deposits), money(discounts)]], headStyles: { fillColor: [32, 33, 36], textColor: 255, halign: 'center' }, bodyStyles: { textColor: [160, 82, 48], fontStyle: 'bold', halign: 'center' }, styles: { fontSize: 10, cellPadding: 9 } })
  document.setTextColor(100, 98, 92); document.setFontSize(9); document.text(`Budget cap: ${options.budgetCap ? money(options.budgetCap) : 'Not configured'} · ${budgetUse.toFixed(1)}% used · ${paid}/${rows.length} paid entries`, 40, 170)
  const columns = ['Date', 'Slot', 'Vendor', 'Plan Type', 'Pax', 'Base/Pax', 'Delivery', 'Courier', 'Dist(km)', 'Pack Fee', 'Deposit', 'Deposit Status', 'Add-on Item', 'Add-on Price', 'Voucher', 'Discount', 'Payment Status', 'Payment Method', 'On-Time', 'Rating', 'Condition', 'Net Total', 'Menu Notes']
  const body = rows.map((row) => [dateLabel(row.date), row.meal, row.vendor, row.planType, `${row.pax}x`, money(row.basePrice), money(row.deliveryFee), row.courierType, row.shippingDistanceKm.toFixed(1), money(row.packagingFee), money(row.packagingDeposit), row.depositStatus, row.addonItems || '-', money(row.addonPrice), row.voucherCode || '-', money(row.discount), row.paymentStatus, row.paymentMethod, row.onTimeStatus, String(row.qualityRating), row.packagingCondition, money(row.netTotal), row.menuNotes || '-'])
  autoTable(document, { startY: 188, head: [columns], body, theme: 'grid', styles: { fontSize: 6.5, cellPadding: 3, overflow: 'linebreak', valign: 'middle' }, headStyles: { fillColor: [32, 33, 36], textColor: 255, fontSize: 6.5 }, alternateRowStyles: { fillColor: [250, 249, 247] }, foot: [['TOTAL', '', '', '', `${totalPax}x`, '', money(rows.reduce((sum, row) => sum + row.deliveryFee, 0)), '', '', money(rows.reduce((sum, row) => sum + row.packagingFee, 0)), money(deposits), '', '', money(rows.reduce((sum, row) => sum + row.addonPrice, 0)), '', money(discounts), '', '', '', '', '', money(totalSpend), '']], footStyles: { fillColor: [245, 240, 236], textColor: [32, 33, 36], fontStyle: 'bold', fontSize: 6.5 } })
  const vendors = [...new Set(rows.map((row) => row.vendor))].map((vendor) => { const items = rows.filter((row) => row.vendor === vendor); return [vendor, String(items.length), money(items.reduce((sum, item) => sum + item.netTotal, 0)), (items.reduce((sum, item) => sum + item.qualityRating, 0) / items.length).toFixed(1), `${Math.round(items.filter((item) => item.onTimeStatus === 'On-Time').length / items.length * 100)}%`] }).sort((a, b) => Number(b[1]) - Number(a[1]))
  const nextY = (document as jsPDF & { lastAutoTable?: { finalY: number } }).lastAutoTable?.finalY ?? 400; document.setTextColor(32, 33, 36); document.setFontSize(13); document.text('Vendor Performance Leaderboard', 40, nextY + 32); autoTable(document, { startY: nextY + 42, head: [['Vendor', 'Entries', 'Total Spend', 'Avg Rating', 'On-Time %']], body: vendors.length ? vendors : [['No data', '0', money(0), '0.0', '0%']], theme: 'grid', headStyles: { fillColor: [32, 33, 36], textColor: 255 }, styles: { fontSize: 8, cellPadding: 5 } }); document.setFontSize(8); document.setTextColor(140, 138, 130); document.text('Generated by Catering Pulse · Full detail report', 40, 820); document.save(`catering-pulse-audit-${new Date().toISOString().slice(0, 10)}.pdf`)
}
