import ExcelJS from 'exceljs'
import { saveAs } from 'file-saver'

export interface ExcelRow { date: string; meal: string; vendor: string; planType: string; pax: number; basePrice: number; deliveryFee: number; courierType: string; shippingDistanceKm: number; packagingFee: number; packagingDeposit: number; depositStatus: string; addonItems: string; addonPrice: number; voucherCode: string; discount: number; paymentStatus: string; paymentMethod: string; onTimeStatus: string; qualityRating: number; packagingCondition: string; netTotal: number; menuNotes: string }
export interface ExcelReportOptions { periodLabel?: string; budgetCap?: number; userName?: string }

const moneyFormat = '"Rp"#,##0'; const headerFill = { type: 'pattern' as const, pattern: 'solid' as const, fgColor: { argb: 'FF202124' } }; const totalFill = { type: 'pattern' as const, pattern: 'solid' as const, fgColor: { argb: 'FFF5F0EC' } }; const border = { top: { style: 'thin' as const, color: { argb: 'FFE5E3DE' } }, left: { style: 'thin' as const, color: { argb: 'FFE5E3DE' } }, bottom: { style: 'thin' as const, color: { argb: 'FFE5E3DE' } }, right: { style: 'thin' as const, color: { argb: 'FFE5E3DE' } } }
function styleHeader(sheet: ExcelJS.Worksheet) { const row = sheet.getRow(1); row.height = 25; row.font = { bold: true, color: { argb: 'FFFFFFFF' }, name: 'Arial' }; row.fill = headerFill; row.alignment = { vertical: 'middle' }; row.eachCell((cell) => { cell.border = border }) }
function styleRows(sheet: ExcelJS.Worksheet, totalRow?: ExcelJS.Row) { sheet.eachRow((row, rowNumber) => { row.font = { ...row.font, name: 'Arial' }; row.eachCell((cell) => { cell.border = border }); if (rowNumber > 1 && (!totalRow || rowNumber < totalRow.number) && rowNumber % 2 === 0) row.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFFAF9F7' } } }); if (totalRow) { totalRow.font = { bold: true, color: { argb: 'FF202124' }, name: 'Arial' }; totalRow.fill = totalFill; totalRow.eachCell((cell) => { cell.border = border }) } }

export async function exportTransactionsExcel(rows: ExcelRow[], options: ExcelReportOptions = {}): Promise<void> {
  const workbook = new ExcelJS.Workbook(); workbook.creator = 'Catering Pulse'; workbook.created = new Date(); const end = Math.max(rows.length + 1, 2)
  const log = workbook.addWorksheet('Catering Log'); log.views = [{ state: 'frozen', ySplit: 1 }]; log.autoFilter = 'A1:W1'; log.columns = [
    { header: 'Date', key: 'date', width: 14 }, { header: 'Slot', key: 'meal', width: 12 }, { header: 'Vendor', key: 'vendor', width: 24 }, { header: 'Plan Type', key: 'planType', width: 18 }, { header: 'Pax', key: 'pax', width: 9 }, { header: 'Base/Pax', key: 'basePrice', width: 15 }, { header: 'Delivery', key: 'deliveryFee', width: 15 }, { header: 'Courier', key: 'courierType', width: 22 }, { header: 'Dist (km)', key: 'shippingDistanceKm', width: 11 }, { header: 'Pack Fee', key: 'packagingFee', width: 14 }, { header: 'Deposit', key: 'packagingDeposit', width: 14 }, { header: 'Deposit Status', key: 'depositStatus', width: 17 }, { header: 'Add-on Item', key: 'addonItems', width: 22 }, { header: 'Add-on Price', key: 'addonPrice', width: 15 }, { header: 'Voucher', key: 'voucherCode', width: 14 }, { header: 'Discount', key: 'discount', width: 14 }, { header: 'Payment Status', key: 'paymentStatus', width: 22 }, { header: 'Payment Method', key: 'paymentMethod', width: 18 }, { header: 'On-Time', key: 'onTimeStatus', width: 12 }, { header: 'Rating', key: 'qualityRating', width: 9 }, { header: 'Condition', key: 'packagingCondition', width: 19 }, { header: 'Net Total', key: 'netTotal', width: 17 }, { header: 'Menu Notes', key: 'menuNotes', width: 35 },
  ]
  rows.forEach((item) => { const row = log.addRow(item); row.getCell(22).value = { formula: `E${row.number}*F${row.number}+G${row.number}+J${row.number}+N${row.number}-P${row.number}` } })
  const totalRow = log.addRow({ vendor: 'TOTAL', pax: { formula: `SUM(E2:E${end})` }, deliveryFee: { formula: `SUM(G2:G${end})` }, packagingFee: { formula: `SUM(J2:J${end})` }, packagingDeposit: { formula: `SUM(K2:K${end})` }, addonPrice: { formula: `SUM(N2:N${end})` }, discount: { formula: `SUM(P2:P${end})` }, netTotal: { formula: `SUM(V2:V${end})` } })
  styleHeader(log); styleRows(log, totalRow); ['basePrice', 'deliveryFee', 'packagingFee', 'packagingDeposit', 'addonPrice', 'discount', 'netTotal'].forEach((key) => { log.getColumn(key).numFmt = moneyFormat }); log.getColumn('pax').numFmt = '#,##0'; log.getColumn('shippingDistanceKm').numFmt = '0.0'

  const summary = workbook.addWorksheet('Summary'); summary.columns = [{ header: 'Metric', key: 'metric', width: 30 }, { header: 'Value', key: 'value', width: 26 }]
  summary.addRows([['Report period', options.periodLabel ?? 'Selected period'], ['Prepared for', options.userName ?? 'Personal workspace'], ['Total transactions', { formula: `COUNTA('Catering Log'!A2:A${end})` }], ['Total spend', { formula: `SUM('Catering Log'!V2:V${end})` }], ['Total pax served', { formula: `SUM('Catering Log'!E2:E${end})` }], ['Average cost / pax', { formula: '=IF(B6=0,0,B5/B6)' }], ['Logistics spend', { formula: `SUM('Catering Log'!G2:G${end})+SUM('Catering Log'!J2:J${end})` }], ['Active deposits', { formula: `SUM('Catering Log'!K2:K${end})` }], ['Discounts', { formula: `SUM('Catering Log'!P2:P${end})` }], ['Paid entries', { formula: `COUNTIF('Catering Log'!Q2:Q${end},"Paid")` }], ['Budget cap', options.budgetCap ?? 0], ['Budget used %', { formula: '=IF(B12=0,0,B5/B12)' }], ['Budget remaining', { formula: '=B12-B5' }]])
  styleHeader(summary); styleRows(summary); [5, 7, 8, 9, 12, 14].forEach((row) => { summary.getCell(`B${row}`).numFmt = moneyFormat }); [4, 6, 11].forEach((row) => { summary.getCell(`B${row}`).numFmt = '#,##0' }); summary.getCell('B13').numFmt = '0.0%'

  const vendors = workbook.addWorksheet('Vendor Performance'); vendors.columns = [{ header: 'Vendor', key: 'vendor', width: 27 }, { header: 'Entries', key: 'entries', width: 12 }, { header: 'Total Spend', key: 'spend', width: 20 }, { header: 'Avg Rating', key: 'rating', width: 14 }, { header: 'On-Time %', key: 'onTime', width: 15 }, { header: 'Paid Rate', key: 'paidRate', width: 15 }]
  ;[...new Set(rows.map((row) => row.vendor))].forEach((vendor, index) => { const r = index + 2; vendors.addRow({ vendor, entries: { formula: `COUNTIF('Catering Log'!C2:C${end},A${r})` }, spend: { formula: `SUMIF('Catering Log'!C2:C${end},A${r},'Catering Log'!V2:V${end})` }, rating: { formula: `IF(B${r}=0,0,AVERAGEIF('Catering Log'!C2:C${end},A${r},'Catering Log'!T2:T${end}))` }, onTime: { formula: `IF(B${r}=0,0,COUNTIFS('Catering Log'!C2:C${end},A${r},'Catering Log'!S2:S${end},"On-Time")/B${r})` }, paidRate: { formula: `IF(B${r}=0,0,COUNTIFS('Catering Log'!C2:C${end},A${r},'Catering Log'!Q2:Q${end},"Paid")/B${r})` } }) })
  styleHeader(vendors); styleRows(vendors); vendors.getColumn('spend').numFmt = moneyFormat; vendors.getColumn('rating').numFmt = '0.0'; vendors.getColumn('onTime').numFmt = '0.0%'; vendors.getColumn('paidRate').numFmt = '0.0%'
  const buffer = await workbook.xlsx.writeBuffer(); saveAs(new Blob([buffer]), `catering-pulse-audit-${new Date().toISOString().slice(0, 10)}.xlsx`)
}
